"""
RecoverAI - Execution Layer
============================

Purpose:
    Execute recovery decisions generated by the Policy Layer.

Modes:

    USE_RAZORPAY = False
        -> Safe synthetic batch evaluation.
        -> No Razorpay API calls.
        -> Recommended for the 75/300 record evaluation.

    USE_RAZORPAY = True
        -> Creates real Razorpay Test Mode Payment Links.
        -> Use only for controlled demonstrations.

IMPORTANT:
    "sent" means the recovery action was executed/simulated.

    "sent" DOES NOT mean money was recovered.

    Actual recovery will be recorded by the webhook layer
    after a successful payment.
"""

import os
import time

import pandas as pd
import razorpay
from dotenv import load_dotenv

import sys

if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8")

from audit_metrics_layer import log_execution_outcome


# ============================================================
# 1. EXECUTION MODE
# ============================================================

# False = synthetic batch evaluation
# True  = real Razorpay Test Mode execution

USE_RAZORPAY = False


# ============================================================
# 2. PROJECT PATHS
# ============================================================

BASE_DIR = os.path.dirname(
    os.path.dirname(
        os.path.abspath(__file__)
    )
)

ENV_PATH = os.path.join(
    BASE_DIR,
    "backend",
    ".env"
)

OUTPUT_DIR = os.path.join(
    BASE_DIR,
    "outputs"
)

POLICY_CSV = os.path.join(
    OUTPUT_DIR,
    "policy_decisions.csv"
)

DETECTION_CSV = os.path.join(
    BASE_DIR,
    "razorpay_failed_payments_synthetic (1).csv"
)


# ============================================================
# 3. OUTPUT DIRECTORY
# ============================================================

os.makedirs(
    OUTPUT_DIR,
    exist_ok=True
)


# ============================================================
# 4. LOAD ENVIRONMENT
# ============================================================

load_dotenv(
    ENV_PATH
)


# ============================================================
# 5. RAZORPAY SETUP
# ============================================================

key_id = os.getenv(
    "RAZORPAY_KEY_ID"
)

key_secret = os.getenv(
    "RAZORPAY_KEY_SECRET"
)


print(
    "Key ID loaded:",
    bool(key_id)
)

print(
    "Key Secret loaded:",
    bool(key_secret)
)


# Only require Razorpay credentials when
# real execution mode is enabled.

if USE_RAZORPAY:

    if not key_id or not key_secret:

        raise RuntimeError(
            "Razorpay credentials not found. "
            "Check backend/.env"
        )

    client = razorpay.Client(
        auth=(
            key_id,
            key_secret
        )
    )

else:

    client = None


# ============================================================
# 6. REAL RAZORPAY PAYMENT LINK
# ============================================================

def attempt_retry_now(
    payment_id,
    amount,
    customer_id=""
):
    """
    Creates a real Razorpay Test Mode Payment Link.

    Returns:

        status
        recovered_amount
        notes

    IMPORTANT:

        Creating a Payment Link does NOT mean
        money has been recovered.
    """

    try:

        # ----------------------------------------------------
        # Validate payment ID
        # ----------------------------------------------------

        if pd.isna(payment_id):

            return (
                "failed",
                0,
                "Missing payment_id"
            )

        payment_id = str(
            payment_id
        ).strip()

        if not payment_id:

            return (
                "failed",
                0,
                "Empty payment_id"
            )

        # ----------------------------------------------------
        # Validate amount
        # ----------------------------------------------------

        if pd.isna(amount):

            return (
                "failed",
                0,
                "Amount is missing"
            )

        amount = float(
            amount
        )

        if amount <= 0:

            return (
                "failed",
                0,
                f"Invalid amount: {amount}"
            )

        # Razorpay uses paise

        amount_paise = int(
            round(
                amount * 100
            )
        )

        if amount_paise <= 0:

            return (
                "failed",
                0,
                "Amount in paise is zero"
            )

        # ----------------------------------------------------
        # Unique recovery reference
        # ----------------------------------------------------

        reference_id = (
            f"recovery_{payment_id}"
        )

        # ----------------------------------------------------
        # Payment Link data
        # ----------------------------------------------------

        payment_link_data = {

            "amount": amount_paise,

            "currency": "INR",

            "description": (
                f"Recovery for failed payment "
                f"{payment_id}"
            ),

            "reference_id": reference_id,

            "notes": {

                "original_payment_id":
                    payment_id
            }
        }

        if customer_id:

            payment_link_data[
                "notes"
            ][
                "customer_id"
            ] = str(
                customer_id
            )

        # ----------------------------------------------------
        # Razorpay API call
        # ----------------------------------------------------

        link = client.payment_link.create(
            payment_link_data
        )

        link_id = link.get(
            "id"
        )

        short_url = link.get(
            "short_url"
        )

        print()
        print(
            f"SUCCESS: {payment_id}"
        )

        print(
            f"Payment Link ID: {link_id}"
        )

        if short_url:

            print(
                f"Payment Link URL: {short_url}"
            )

        notes = (
            f"payment_link_id={link_id}; "
            f"payment_link_url={short_url}; "
            f"reference_id={reference_id}; "
            f"amount={amount}"
        )

        # Payment link created.
        # Customer has NOT paid yet.

        return (
            "sent",
            0,
            notes
        )

    except Exception as e:

        print()
        print(
            f"FAILED: {payment_id}"
        )

        print(
            f"Reason: {e}"
        )

        return (
            "failed",
            0,
            str(e)
        )


# ============================================================
# 7. SYNTHETIC EXECUTION
# ============================================================

def simulate_retry_now(
    payment_id,
    amount,
    customer_id=""
):
    """
    Simulates the recovery action for batch evaluation.

    This does NOT call Razorpay.

    It represents what the agent would execute
    in a production environment.
    """

    try:

        amount = float(
            amount
        )

    except Exception:

        return (
            "failed",
            0,
            "Invalid amount"
        )

    if amount <= 0:

        return (
            "failed",
            0,
            f"Invalid amount: {amount}"
        )

    notes = (
        "SIMULATED recovery action; "
        "Razorpay execution disabled "
        "for batch evaluation"
    )

    print(
        f"SIMULATED: {payment_id} "
        f"-> retry_now "
        f"-> ₹{amount:.2f}"
    )

    return (
        "sent",
        0,
        notes
    )


# ============================================================
# 8. MAIN EXECUTION
# ============================================================

def run_execution():

    print()
    print(
        "=" * 60
    )

    print(
        "RecoverAI - Execution Layer"
    )

    print(
        "=" * 60
    )

    print(
        "Mode:",
        "RAZORPAY TEST MODE"
        if USE_RAZORPAY
        else "SYNTHETIC BATCH"
    )

    print()

    # --------------------------------------------------------
    # Check policy file
    # --------------------------------------------------------

    if not os.path.exists(
        POLICY_CSV
    ):

        raise FileNotFoundError(
            f"Policy file not found:\n"
            f"{POLICY_CSV}"
        )

    # --------------------------------------------------------
    # Check detection file
    # --------------------------------------------------------

    if not os.path.exists(
        DETECTION_CSV
    ):

        raise FileNotFoundError(
            f"Detection file not found:\n"
            f"{DETECTION_CSV}"
        )

    # --------------------------------------------------------
    # Load files
    # --------------------------------------------------------

    policy = pd.read_csv(
        POLICY_CSV
    )

    detection = pd.read_csv(
        DETECTION_CSV
    )

    print(
        f"Policy records: "
        f"{len(policy)}"
    )

    print(
        f"Detection records: "
        f"{len(detection)}"
    )

    # --------------------------------------------------------
    # Validate policy columns
    # --------------------------------------------------------

    required_policy_columns = [
        "payment_id",
        "action"
    ]

    for column in required_policy_columns:

        if column not in policy.columns:

            raise ValueError(
                f"Missing column in "
                f"policy_decisions.csv: "
                f"{column}"
            )

    # --------------------------------------------------------
    # Validate detection columns
    # --------------------------------------------------------

    required_detection_columns = [
        "payment_id",
        "amount"
    ]

    for column in required_detection_columns:

        if column not in detection.columns:

            raise ValueError(
                f"Missing column in detection CSV: "
                f"{column}"
            )

    # --------------------------------------------------------
    # Payment amount lookup
    # --------------------------------------------------------

    amounts = (
        detection
        .drop_duplicates(
            "payment_id"
        )
        .set_index(
            "payment_id"
        )[
            "amount"
        ]
        .to_dict()
    )

    # --------------------------------------------------------
    # Customer lookup
    # --------------------------------------------------------

    if "customer_id" in detection.columns:

        customers = (
            detection
            .drop_duplicates(
                "payment_id"
            )
            .set_index(
                "payment_id"
            )[
                "customer_id"
            ]
            .to_dict()
        )

    else:

        customers = {}

    # --------------------------------------------------------
    # Counters
    # --------------------------------------------------------

    results = {

        "sent": 0,

        "failed": 0,

        "skipped": 0
    }

    # ========================================================
    # PROCESS POLICY DECISIONS
    # ========================================================

    for _, row in policy.iterrows():

        payment_id = str(
            row["payment_id"]
        ).strip()

        action = str(
            row["action"]
        ).strip()

        # ----------------------------------------------------
        # Payment doesn't exist
        # ----------------------------------------------------

        if payment_id not in amounts:

            status = "failed"

            recovered = 0

            notes = (
                "Payment ID not found "
                "in detection data"
            )

        else:

            amount = amounts[
                payment_id
            ]

            customer_id = customers.get(
                payment_id,
                ""
            )

            # =================================================
            # RETRY NOW
            # =================================================

            if action == "retry_now":

                if USE_RAZORPAY:

                    (
                        status,
                        recovered,
                        notes
                    ) = attempt_retry_now(

                        payment_id,

                        amount,

                        customer_id
                    )

                    # Wait between API calls

                    time.sleep(
                        2
                    )

                else:

                    (
                        status,
                        recovered,
                        notes
                    ) = simulate_retry_now(

                        payment_id,

                        amount,

                        customer_id
                    )

            # =================================================
            # RETRY LATER
            # =================================================

            elif action == "retry_later":

                status = "skipped"

                recovered = 0

                notes = (
                    "retry_later not automated yet; "
                    "scheduler required"
                )

            # =================================================
            # SEND REMINDER
            # =================================================

            elif action == "send_reminder":

                status = "skipped"

                recovered = 0

                notes = (
                    "send_reminder not automated yet; "
                    "notification service required"
                )

            # =================================================
            # ESCALATE HUMAN
            # =================================================

            elif action == "escalate_human":

                status = "skipped"

                recovered = 0

                notes = (
                    "Escalated to human review"
                )

            # =================================================
            # UNKNOWN ACTION
            # =================================================

            else:

                status = "skipped"

                recovered = 0

                notes = (
                    f"Unknown action: "
                    f"{action}"
                )

        # ----------------------------------------------------
        # Audit logging
        # ----------------------------------------------------

        log_execution_outcome(

            payment_id,

            action,

            status,

            recovered_amount=recovered,

            notes=notes
        )

        results[
            status
        ] = results.get(
            status,
            0
        ) + 1

    # ========================================================
    # FINAL SUMMARY
    # ========================================================

    print()

    print(
        "=" * 60
    )

    print(
        "EXECUTION RUN COMPLETE"
    )

    print(
        "=" * 60
    )

    print(
        f"  sent:     "
        f"{results['sent']}"
    )

    print(
        f"  failed:   "
        f"{results['failed']}"
    )

    print(
        f"  skipped:  "
        f"{results['skipped']}"
    )

    print(
        "=" * 60
    )

    print()

    print(
        "Execution results logged."
    )

    print(
        "Run audit_metrics_layer.py "
        "to update metrics."
    )

    print()

    print(
        "IMPORTANT:"
    )

    print(
        "sent != recovered"
    )

    print(
        "Actual recovered money will be "
        "recorded by the Razorpay webhook "
        "after a successful payment."
    )


# ============================================================
# 9. START
# ============================================================

if __name__ == "__main__":

    run_execution()